services:
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: timbeck
      POSTGRES_DB: jwt
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "4242:5432"
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
  postgres: