services:
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: timbeck
      POSTGRES_DB: jwt
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "4242:5432"
    networks:
      - postgres
    restart: unless-stopped
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"

networks:
  postgres:
    driver: bridge

volumes:
  postgres: